"""
Django settings for samriddhi project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ogkezh#njzmwv*1kq+cn!u!1ds&qrn*li%p!c%q_l2n$4hx(+-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'master',
    'config',
    'logs',
    'import_export',
    'cache_headers',
    'agency',
    'django_filters',
    'rawsap',
    'mis',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'cache_headers.middleware.CacheHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'samriddhi.urls'


# CACHE_HEADERS = {
#     "timeouts": {
#         "all-users": {
#             60: (
#                 "^/all-users/",
#             )
#         },
#         "anonymous-only": {
#             60: (
#                 "^/anonymous-only/",
#             )
#         },
#         "anonymous-and-authenticated": {
#             60: (
#                 "^/anonymous-and-authenticated/",
#             )
#         },
#         "per-user": {
#             60: (
#                 "^/per-user/",
#             )
#         },
#         "custom-policy": {
#             60: (
#                 "^/custom-policy/",
#             )
#         }
#     }
# }

# CACHE_HEADERS = {"browser-cache-seconds": 10}

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.PyLibMCCache',
#         'LOCATION': '/tmp/memcached.sock',
#     }
# }



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'samriddhi.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ]
}


#Database ye setting sahi hai na? aap dal dijiye sahi
#https://docs.djangoproject.com/en/2.1/ref/settings/#databases host ok done!
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'SAMRIDDHI',
        'HOST' : '10.51.82.122',
        'USER' : 'SAMRIDDHI',
        'PASSWORD' : 'Li73Mu04$',
        'PORT' : '3306',
        'OPTIONS': {
            'read_default_file': os.path.join(BASE_DIR, 'db_config.cnf')
        },
    }
}
# local


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'SAMRIDDHI',
#         'HOST' : '10.51.82.122',
#         'USER' : 'SAMRIDDHI',
#         'PASSWORD' : 'Li73Mu04$',
#         'PORT' : '3306',
#         'OPTIONS': {
#             'read_default_file': os.path.join(BASE_DIR, 'db_config.cnf')
#         },
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'SAMRIDDHI',
#         'HOST' : 'localhost',
#         'USER' : 'root',
#         'PASSWORD' : '',
#         'PORT' : '3306',
#         'OPTIONS': {
#             'read_default_file': os.path.join(BASE_DIR, 'db_config.cnf')
#         },
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'master.UserMaster'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE =  'Asia/Kolkata'
USE_TZ = False

USE_I18N = True

USE_L10N = True
DATETIME_FORMAT = '%d-%m-%Y %H:%M:%S' 



EMAIL_HOST = '10.2.17.14'
EMAIL_PORT = 25
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'


STATICFILES_DIRS = [
     os.path.join(BASE_DIR, "static"),
     '/static/',
]
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
SESSION_EXPIRE_SECONDS = 900
