# Generated by Django 2.2.8 on 2020-09-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZVT_PORTAL_CIR',
            fields=[
                ('zvt_portal_cir_id', models.AutoField(primary_key=True, serialize=False)),
                ('mandt', models.CharField(blank=True, max_length=9, null=True)),
                ('vbeln', models.CharField(blank=True, max_length=30, null=True)),
                ('posnr', models.CharField(blank=True, max_length=18, null=True)),
                ('gjahr', models.CharField(blank=True, max_length=12, null=True)),
                ('monat', models.CharField(blank=True, max_length=6, null=True)),
                ('vkorg', models.CharField(blank=True, max_length=12, null=True)),
                ('vtweg', models.CharField(blank=True, max_length=6, null=True)),
                ('spart', models.CharField(blank=True, max_length=6, null=True)),
                ('pstyv', models.CharField(blank=True, max_length=12, null=True)),
                ('sold_to_party', models.CharField(blank=True, max_length=30, null=True)),
                ('ship_to_party', models.CharField(blank=True, max_length=30, null=True)),
                ('ord_date', models.CharField(blank=True, max_length=24, null=True)),
                ('vgbel', models.CharField(blank=True, max_length=30, null=True)),
                ('bezei', models.CharField(blank=True, max_length=120, null=True)),
                ('drerz', models.CharField(blank=True, max_length=24, null=True)),
                ('pva', models.CharField(blank=True, max_length=24, null=True)),
                ('matnr', models.CharField(blank=True, max_length=54, null=True)),
                ('pub_name', models.CharField(blank=True, max_length=120, null=True)),
                ('soff_name', models.CharField(blank=True, max_length=75, null=True)),
                ('cg_name', models.CharField(blank=True, max_length=60, null=True)),
                ('sdist_name', models.CharField(blank=True, max_length=60, null=True)),
                ('edition_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cust_name', models.CharField(blank=True, max_length=90, null=True)),
                ('city_name', models.CharField(blank=True, max_length=75, null=True)),
                ('vkgrp', models.CharField(blank=True, max_length=9, null=True)),
                ('sgrp_name', models.CharField(blank=True, max_length=75, null=True)),
                ('vkbur', models.CharField(blank=True, max_length=12, null=True)),
                ('kdgrp', models.CharField(blank=True, max_length=6, null=True)),
                ('bzirk', models.CharField(blank=True, max_length=18, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('disc_perc', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('gross_copy', models.IntegerField(blank=True, null=True)),
                ('free_copy', models.IntegerField(blank=True, null=True)),
                ('paid_copy', models.IntegerField(blank=True, null=True)),
                ('zlao', models.IntegerField(blank=True, null=True)),
                ('zcoo', models.IntegerField(blank=True, null=True)),
                ('gross_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('route', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'db_table': 'ZVT_PORTAL_CIR',
            },
        ),
    ]
