# Generated by Django 2.2.8 on 2020-09-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawsap', '0002_zvt_data_account_zvt_portal_bill_zvt_portal_exbp_zvt_portal_invhd_zvt_portal_reg_zvt_portal_regih_zv'),
    ]

    operations = [
        migrations.AddField(
            model_name='zvt_portal_cir',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='zvt_portal_cir',
            name='ord_date_f',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zvt_portal_cir',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
