# Generated by Django 2.2.8 on 2020-09-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawsap', '0003_auto_20200923_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zvt_portal_cir',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='zvt_portal_cir',
            name='update_date',
        ),
    ]
