# Generated by Django 2.1.15 on 2020-03-03 09:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('adalias', models.PositiveSmallIntegerField(default=0)),
                ('bpcode', models.PositiveSmallIntegerField(default=0)),
                ('email', models.EmailField(default='Test@gmail.com', max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'UserMaster',
            },
        ),
        migrations.CreateModel(
            name='AccessTypeMaster',
            fields=[
                ('accesstype_code', models.AutoField(primary_key=True, serialize=False)),
                ('accesstype_text', models.CharField(max_length=100)),
                ('access_type', models.CharField(max_length=20, unique=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.IntegerField(blank=True, null=True)),
                ('update_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AccessTypeMaster',
            },
        ),
        migrations.CreateModel(
            name='UserMasterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('to_date', models.DateField(blank=True, default=datetime.datetime(9999, 12, 31, 0, 0), null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(max_length=50, null=True)),
                ('update_user', models.CharField(max_length=50, null=True)),
                ('last_login_on', models.DateTimeField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('access_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master.AccessTypeMaster', to_field='access_type')),
            ],
            options={
                'db_table': 'UserMasterDetails',
            },
        ),
        migrations.CreateModel(
            name='UserTypeMaster',
            fields=[
                ('usertype_code', models.AutoField(primary_key=True, serialize=False)),
                ('usertype_text', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=20, unique=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.IntegerField(blank=True, null=True)),
                ('update_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UserTypeMaster',
            },
        ),
        migrations.AddField(
            model_name='usermasterdetails',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.UserTypeMaster', to_field='user_type'),
        ),
        migrations.AddField(
            model_name='usermasterdetails',
            name='usermaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
