# Generated by Django 2.1.15 on 2020-03-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20200303_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='username',
            field=models.CharField(default='test', max_length=30, unique=True),
        ),
    ]
