# Generated by Django 2.1.15 on 2020-03-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_usermaster_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='bpcode',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
