# Generated by Django 2.1.15 on 2020-03-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20200303_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertypemaster',
            name='update_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
