# Generated by Django 2.1.15 on 2020-03-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20200303_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermasterdetails',
            name='create_user',
            field=models.CharField(default='test', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermasterdetails',
            name='update_user',
            field=models.CharField(default='test', max_length=50, null=True),
        ),
    ]
