# Generated by Django 2.1.15 on 2020-03-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20200304_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
