# Generated by Django 2.1.5 on 2020-04-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20200304_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
