# Generated by Django 2.1.5 on 2020-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_educationmaster'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='EducationMaster',
        #     fields=[
        #         ('Education_code', models.AutoField(primary_key=True, serialize=False)),
        #         ('Education_text', models.CharField(max_length=100)),
        #         ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
        #         ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
        #         ('update_date', models.DateTimeField(auto_now=True, null=True)),
        #         ('create_user', models.CharField(blank=True, max_length=20, null=True)),
        #         ('update_user', models.CharField(blank=True, max_length=20, null=True)),
        #     ],
        #     options={
        #         'db_table': 'EducationMaster',
        #     },
        # ),
    ]
