# Generated by Django 2.1.15 on 2020-03-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMaster',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False)),
                ('server_text', models.TextField(max_length=50)),
                ('server_host', models.TextField(max_length=50)),
                ('server_username', models.CharField(blank=True, max_length=255, null=True)),
                ('server_password', models.CharField(blank=True, max_length=255, null=True)),
                ('server_status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'ServerMaster',
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('sms_id', models.AutoField(primary_key=True, serialize=False)),
                ('sms_from_page', models.CharField(max_length=20)),
                ('sms_body', models.CharField(max_length=255)),
                ('sms_to', models.CharField(max_length=15)),
                ('sms_response', models.CharField(max_length=255)),
                ('sms_send_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'SmsLog',
            },
        ),
        migrations.CreateModel(
            name='SmsManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_for', models.CharField(max_length=20, unique=True)),
                ('sms_host', models.CharField(max_length=255)),
                ('sms_user', models.CharField(max_length=30)),
                ('sms_password', models.CharField(max_length=25)),
                ('sms_body_first', models.CharField(max_length=255)),
                ('sms_body_second', models.CharField(max_length=255)),
                ('sms_body_third', models.CharField(max_length=255)),
                ('sms_from', models.CharField(max_length=20)),
                ('sms_status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'SmsManager',
            },
        ),
    ]
