# Generated by Django 2.1.5 on 2020-03-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='ContactUs_top',
        ),
        migrations.AddField(
            model_name='contactus',
            name='ContactUs_Bottom',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='ContactUs_Top',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='ContactUs_EmailID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='ContactUs_Number',
            field=models.TextField(max_length=20),
        ),
    ]
