# Generated by Django 2.1.5 on 2020-05-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='Hint_Leng',
            field=models.TextField(default='EN', max_length=2),
        ),
    ]
