# Generated by Django 2.1.5 on 2020-05-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_hint_hint_leng'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategoryMaster',
            fields=[
                ('IncidentCategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('IncidentCategory_Srno', models.IntegerField(blank=True, default=1, null=True)),
                ('IncidentCategory_Text', models.TextField(max_length=255)),
                ('IncidentCategory_Status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'IncidentCategory_Text',
            },
        ),
    ]
