# Generated by Django 2.1.5 on 2020-05-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_incidentcategorymaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatusTypeMaster',
            fields=[
                ('IncidentStatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('IncidentStatus_Srno', models.IntegerField(blank=True, default=1, null=True)),
                ('IncidentStatus_Text', models.TextField(max_length=255)),
                ('IncidentStatus_Status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'IncidentStatusTypeMaster',
            },
        ),
    ]
