# Generated by Django 2.1.5 on 2020-05-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_incidentstatustypemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCommentDetail',
            fields=[
                ('IncidentComment_Number', models.AutoField(primary_key=True, serialize=False)),
                ('IncidentComment_Text', models.TextField(blank=True, max_length=255, null=True)),
                ('IncidentComment_By', models.CharField(blank=True, max_length=30, null=True)),
                ('IncidentComment_On', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=20, null=True)),
                ('update_user', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'IncidentCommentDetail',
            },
        ),
        migrations.CreateModel(
            name='IncidentFeedbackDetail',
            fields=[
                ('IncidentFeedback_Number', models.AutoField(primary_key=True, serialize=False)),
                ('IncidentFeedback_Rating', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('IncidentFeedback_Text', models.TextField(blank=True, max_length=255, null=True)),
                ('IncidentFeedback_By', models.CharField(blank=True, max_length=30, null=True)),
                ('IncidentFeedback_On', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=20, null=True)),
                ('update_user', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'IncidentFeedbackDetail',
            },
        ),
        migrations.CreateModel(
            name='IncidentMaster',
            fields=[
                ('Incident_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Incident_Text', models.TextField(max_length=255)),
                ('Incident_VKORG', models.CharField(blank=True, max_length=10, null=True)),
                ('Incident_BP_CODE', models.CharField(max_length=30)),
                ('Incident_Last_Feedback', models.TextField(blank=True, max_length=255, null=True)),
                ('Incident_Last_Feedback_By', models.CharField(blank=True, max_length=30, null=True)),
                ('Incident_Last_Feedback_On', models.DateTimeField(auto_now_add=True, null=True)),
                ('Incident_Last_Comment', models.TextField(blank=True, max_length=255, null=True)),
                ('Incident_Last_Comment_By', models.CharField(blank=True, max_length=30, null=True)),
                ('Incident_Last_Comment_On', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=20, null=True)),
                ('update_user', models.CharField(blank=True, max_length=20, null=True)),
                ('Incident_Cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.IncidentCategoryMaster')),
                ('Incident_Status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='config.IncidentStatusTypeMaster')),
            ],
            options={
                'db_table': 'IncidentMaster',
            },
        ),
        migrations.AddField(
            model_name='incidentfeedbackdetail',
            name='Incident_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.IncidentMaster'),
        ),
        migrations.AddField(
            model_name='incidentcommentdetail',
            name='Incident_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.IncidentMaster'),
        ),
        migrations.AddField(
            model_name='incidentcommentdetail',
            name='Incident_Status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='config.IncidentStatusTypeMaster'),
        ),
    ]
