# Generated by Django 2.1.5 on 2020-06-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_auto_20200527_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmaster',
            name='Incident_Last_assigned_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentmaster',
            name='Incident_Last_assigned_to_Level',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='incidentmaster',
            name='Incident_Last_assigned_to_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidentmaster',
            name='Incident_Last_assigned_to_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
