# Generated by Django 2.1.5 on 2020-06-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_auto_20200602_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmaster',
            name='Incident_STATE',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
