# Generated by Django 2.1.5 on 2020-06-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_educationmaster'),
        ('config', '0010_incidentmaster_incident_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentcommentdetail',
            name='IncidentComment_By_Level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master.AccessTypeMaster', to_field='access_type'),
        ),
        migrations.AddField(
            model_name='incidentcommentdetail',
            name='IncidentComment_By_Name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
