# Generated by Django 2.1.5 on 2020-06-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_auto_20200602_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBodyMaster',
            fields=[
                ('EmailBody_Number', models.AutoField(primary_key=True, serialize=False)),
                ('EmailBody_For', models.CharField(blank=True, max_length=30, null=True)),
                ('EmailBody_Len', models.CharField(blank=True, default='EN', max_length=2, null=True)),
                ('EmailBody_Subject', models.TextField(blank=True, max_length=255, null=True)),
                ('EmailBody_Header', models.TextField(blank=True, max_length=255, null=True)),
                ('EmailBody_Line1', models.TextField(blank=True, max_length=255, null=True)),
                ('EmailBody_Line2', models.TextField(blank=True, max_length=255, null=True)),
                ('EmailBody_Line3', models.TextField(blank=True, max_length=255, null=True)),
                ('EmailBody_Line4', models.TextField(blank=True, max_length=255, null=True)),
                ('EmailBody_Line5', models.TextField(blank=True, max_length=255, null=True)),
                ('EmailBody_Line6', models.TextField(blank=True, max_length=255, null=True)),
                ('EmailBody_Bottom', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=20, null=True)),
                ('update_user', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'EmailBodyMaster',
            },
        ),
    ]
