# Generated by Django 2.0.2 on 2020-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_billconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='billconfirmation',
            name='Device_On',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billconfirmation',
            name='Confirm_By',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
