# Generated by Django 2.0.2 on 2020-07-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_auto_20200629_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransactionPRD',
            fields=[
                ('Transaction_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Transaction_Bank', models.CharField(default='IDBI BANK', max_length=50)),
                ('pan', models.CharField(max_length=16)),
                ('van', models.CharField(max_length=16)),
                ('tranAmt', models.CharField(max_length=20)),
                ('trandate', models.DateTimeField(auto_now_add=True)),
                ('Rem_name', models.CharField(max_length=100)),
                ('Rem_name_rbi', models.CharField(blank=True, max_length=100, null=True)),
                ('utr', models.CharField(max_length=35, unique=True)),
                ('mode', models.CharField(max_length=15)),
                ('Sender_receiver_info', models.CharField(blank=True, max_length=200, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=15, null=True)),
                ('RemitterAcctNo', models.CharField(blank=True, max_length=35, null=True)),
                ('Response_To_Bank', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Bank_Response_Json', models.TextField(blank=True, max_length=5000, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=20, null=True)),
                ('update_user', models.CharField(blank=True, max_length=20, null=True)),
                ('get_from_bank_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('Post_To_SAP', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Post_To_SAP_on', models.DateTimeField(blank=True, null=True)),
                ('SAP_sent_Json', models.TextField(blank=True, max_length=5000, null=True)),
                ('SAP_response_Json', models.TextField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'BankTransactionPRD',
            },
        ),
    ]
