# Generated by Django 2.0.2 on 2020-07-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_banktransactionprd'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankList',
            fields=[
                ('Bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('Bank_Name', models.CharField(max_length=255, unique=True)),
                ('Bank_Type', models.CharField(blank=True, max_length=30, null=True)),
                ('Bank_URL', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=20, null=True)),
                ('update_user', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'BankList',
            },
        ),
        migrations.AddField(
            model_name='billconfirmation',
            name='Bill_Amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billconfirmation',
            name='Bill_copies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
