# Generated by Django 2.0.2 on 2020-07-24 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0017_auto_20200717_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TockenUser',
            fields=[
                ('Tocken_id', models.AutoField(primary_key=True, serialize=False)),
                ('Tocken_code', models.CharField(max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=20, null=True)),
                ('update_user', models.CharField(blank=True, max_length=20, null=True)),
                ('usermaster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TockenUser',
            },
        ),
    ]
