# Generated by Django 2.2.8 on 2020-08-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_notificationcategorymaster_notificationlog_salesorgmaster_statemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='Notification_Category',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
