# Generated by Django 2.2.8 on 2020-08-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_auto_20200807_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='tockenuser',
            name='Notification_Leng',
            field=models.CharField(blank=True, default='EN', max_length=100, null=True),
        ),
    ]
