# Generated by Django 2.1.15 on 2020-03-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegLog',
            fields=[
                ('reg_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('PARTNER', models.CharField(blank=True, max_length=100, null=True)),
                ('adalias', models.CharField(max_length=30, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('reg_device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'RegLog',
            },
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('user_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('log_action', models.CharField(max_length=50)),
                ('log_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('log_host', models.CharField(blank=True, max_length=50, null=True)),
                ('log_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('browser_type', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'UserLog',
            },
        ),
    ]
