# Generated by Django 2.1.15 on 2020-03-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglog',
            name='adalias',
            field=models.CharField(max_length=30),
        ),
    ]
