# Generated by Django 2.1.5 on 2020-04-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20200304_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='log_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userlogs',
            name='log_action',
            field=models.CharField(max_length=250),
        ),
    ]
