# Generated by Django 2.1.5 on 2020-05-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20200424_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('PaymentLog_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('Payment_Request', models.CharField(blank=True, max_length=250, null=True)),
                ('Payment_Response', models.CharField(blank=True, max_length=250, null=True)),
                ('Payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Payment_diviceID', models.CharField(blank=True, max_length=50, null=True)),
                ('Payment_Status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'PaymentLog',
            },
        ),
    ]
