# Generated by Django 2.1.5 on 2020-05-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='Payment_Amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
