# Generated by Django 2.1.5 on 2020-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_auto_20200502_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='SAPPOST_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='SAPPOST_status',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='SAP_Request',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='SAP_Response',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
