# Generated by Django 2.2 on 2020-09-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_educationmaster'),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMaster',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_SAPcode', models.TextField(max_length=50)),
                ('team_name', models.TextField(max_length=250)),
                ('team_email', models.CharField(blank=True, max_length=50, null=True)),
                ('team_mono', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=20, null=True)),
                ('update_user', models.CharField(blank=True, max_length=20, null=True)),
                ('access_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='master.AccessTypeMaster', to_field='access_type')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.StateMaster')),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.UnitMaster')),
            ],
            options={
                'db_table': 'TeamMaster',
            },
        ),
    ]
