# Generated by Django 2.2.8 on 2020-09-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_teammaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencyrequestmaster',
            old_name='state_id',
            new_name='StateMaster',
        ),
    ]
