# Generated by Django 2.2.8 on 2020-09-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20200910_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencyrequestmaster',
            old_name='StateMaster',
            new_name='state_id',
        ),
    ]
