# Generated by Django 2.2.8 on 2020-09-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20200910_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency_child',
            name='kybp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Agency_Child_set', to='agency.AgencyRequestKYBP'),
        ),
        migrations.AlterField(
            model_name='agency_othernewspaper',
            name='kybp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Agency_OtherNewsPaper_set', to='agency.AgencyRequestKYBP'),
        ),
        migrations.AlterField(
            model_name='agencyrequestagdetail',
            name='ag_req_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AgencyRequestAGDetail_set', to='agency.AgencyRequestMaster'),
        ),
        migrations.AlterField(
            model_name='agencyrequestcirreq',
            name='ag_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AgencyRequestCIRReq_set', to='agency.AgencyRequestAGDetail'),
        ),
        migrations.AlterField(
            model_name='agencyrequestkybp',
            name='ag_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AgencyRequestKYBP_set', to='agency.AgencyRequestAGDetail'),
        ),
        migrations.AlterField(
            model_name='agencyrequestreason',
            name='ag_req_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AgencyRequestReason_set', to='agency.AgencyRequestMaster'),
        ),
        migrations.AlterField(
            model_name='agencyrequestsurvey',
            name='ag_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AgencyRequestSurvey_set', to='agency.AgencyRequestAGDetail'),
        ),
        migrations.AlterField(
            model_name='agencyrequestsurveytarget',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AgencyRequestSurveyTarget_set', to='agency.AgencyRequestSurvey'),
        ),
        migrations.AlterField(
            model_name='agencyrequestsurveyvillage',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AgencyRequestSurveyVillage_set', to='agency.AgencyRequestSurvey'),
        ),
        migrations.AlterField(
            model_name='cirreqcheque',
            name='cirreq_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CirReqCheque_set', to='agency.AgencyRequestCIRReq'),
        ),
        migrations.AlterField(
            model_name='cirreqdropping',
            name='cirreq_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CirReqDropping_set', to='agency.AgencyRequestCIRReq'),
        ),
        migrations.AlterField(
            model_name='cirreqedition',
            name='cirreq_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CirReqEdition_set', to='agency.AgencyRequestCIRReq'),
        ),
    ]
