# Generated by Django 2.2.8 on 2020-09-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20200918_1743'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='editionmaster',
        #     name='plant_id',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.PlantMaster'),
        # ),
        # migrations.AddField(
        #     model_name='editionmaster',
        #     name='unit_id',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.UnitMaster'),
        # ),
        migrations.AddField(
            model_name='statemaster',
            name='state_sapcode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ASDMaster',
            fields=[
                ('asd_id', models.AutoField(primary_key=True, serialize=False)),
                ('asd', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('from_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('to_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=20, null=True)),
                ('update_user', models.CharField(blank=True, max_length=20, null=True)),
                ('publication_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.PublicationMaster')),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.UnitMaster')),
            ],
            options={
                'db_table': 'ASDMaster',
            },
        ),
    ]
