# Generated by Django 2.2.8 on 2020-09-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20200922_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statemaster',
            name='state_sapcode',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
