# Generated by Django 2.2.8 on 2020-09-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_auto_20200922_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionmaster',
            name='plant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.PlantMaster'),
        ),
        migrations.AddField(
            model_name='editionmaster',
            name='unit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.UnitMaster'),
        ),
    ]
