# Generated by Django 2.2.8 on 2020-09-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_auto_20200922_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceGroupMaster',
            fields=[
                ('price_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_group', models.CharField(blank=True, max_length=2, null=True)),
                ('min_copy_limit', models.IntegerField(blank=True, null=True)),
                ('max_copy_limit', models.IntegerField(blank=True, null=True)),
                ('comm_per', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_group_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('to_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=20, null=True)),
                ('update_user', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.UnitMaster')),
            ],
            options={
                'db_table': 'PriceGroupMaster',
            },
        ),
    ]
