# Generated by Django 2.2.8 on 2020-09-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_pricegroupmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='asdmaster',
            name='sales_group',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asdmaster',
            name='sales_office',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
