# Generated by Django 2.2.8 on 2020-09-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_auto_20200922_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOffMaster',
            fields=[
                ('salesoff_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_office', models.CharField(max_length=4)),
                ('status', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.CharField(blank=True, max_length=20, null=True)),
                ('update_user', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.UnitMaster')),
            ],
            options={
                'db_table': 'SalesOffMaster',
            },
        ),
    ]
