# Generated by Django 2.2.8 on 2020-09-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_clustermaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdistmaster',
            name='sales_dist_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
