# Generated by Django 2.2.8 on 2020-09-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_auto_20200923_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyrequestagdetail',
            name='cluster_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.ClusterMaster'),
        ),
        migrations.AddField(
            model_name='agencyrequestagdetail',
            name='custgrp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agencyrequestagdetail',
            name='price_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.PriceGroupMaster'),
        ),
        migrations.AddField(
            model_name='agencyrequestagdetail',
            name='salesdist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.SalesDistMaster'),
        ),
        migrations.AddField(
            model_name='agencyrequestagdetail',
            name='salesoff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.SalesOffMaster'),
        ),
        migrations.AddField(
            model_name='agencyrequestkybp',
            name='ag_title',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('M/s', 'M/s')], default='Mr', max_length=20),
        ),
    ]
